In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
df = pd.read_csv('../50039bsc.csv', delimiter=';', encoding='latin-1')
df['Total'] = df.Total.apply(lambda x: float(x.replace(',', '.')))
df.head()

,Comunidades y Ciudades Autónomas,Tipo de equipamiento,periodo,Total
0,Andalucía,Viviendas con algún tipo de ordenador,2021,78.6
1,Andalucía,Viviendas con algún tipo de ordenador,2020,76.8
2,Andalucía,Viviendas con algún tipo de ordenador,2019,76.8
3,Andalucía,Viviendas con algún tipo de ordenador,2018,74.4
4,Andalucía,Viviendas con algún tipo de ordenador,2017,74.3

In [3]:
df.columns

Index(['Comunidades y Ciudades Autónomas', 'Tipo de equipamiento', 'periodo',
       'Total'],
      dtype='object')

In [4]:
comunidades = df['Comunidades y Ciudades Autónomas'].unique() 
comunidades

array(['Andalucía', 'Aragón', 'Asturias (Principado de)',
       'Balears (Illes)', 'Canarias', 'Cantabria', 'Castilla y León',
       'Castilla-La Mancha', 'Cataluña', 'Comunitat Valenciana',
       'Extremadura', 'Galicia', 'Madrid (Comunidad de)',
       'Murcia (Región de)', 'Navarra (Comunidad Foral de)', 'País Vasco',
       'Rioja (La)', 'Ceuta', 'Melilla'], dtype=object)

In [5]:
equipamiento = df.loc[:,'Tipo de equipamiento'].unique()
equipamiento

array(['Viviendas con algún tipo de ordenador',
       'Viviendas que disponen de acceso a Internet',
       'Viviendas con conexión de Banda Ancha',
       'Viviendas con  teléfono fijo', 'Viviendas con  teléfono móvil'],
      dtype=object)

In [28]:
periodo_max = max(df.loc[:,'periodo'])
periodo_min = min(df.loc[:,'periodo'])
print(periodo_max, periodo_min)

2021 2006

In [32]:
filtered_df = df[df['Comunidades y Ciudades Autónomas'].isin(['Andalucía','Asturias (Principado de)'])]
filtered_df = filtered_df[filtered_df['Tipo de equipamiento'].isin(['Viviendas que disponen de acceso a Internet'])]
filtered_df = filtered_df[(filtered_df['periodo'] >= 2006) & (filtered_df['periodo'] <= 2021)]
filtered_df

,Comunidades y Ciudades Autónomas,Tipo de equipamiento,periodo,Total
16,Andalucía,Viviendas que disponen de acceso a Internet,2021,94.5
17,Andalucía,Viviendas que disponen de acceso a Internet,2020,94.7
18,Andalucía,Viviendas que disponen de acceso a Internet,2019,89.7
19,Andalucía,Viviendas que disponen de acceso a Internet,2018,83.7
20,Andalucía,Viviendas que disponen de acceso a Internet,2017,81.7
21,Andalucía,Viviendas que disponen de acceso a Internet,2016,80.6
22,Andalucía,Viviendas que disponen de acceso a Internet,2015,76.4
23,Andalucía,Viviendas que disponen de acceso a Internet,2014,72.7
24,Andalucía,Viviendas que disponen de acceso a Internet,2013,66.3
25,Andalucía,Viviendas que disponen de acceso a Internet,2012,63.3
26,Andalucía,Viviendas que disponen de acceso a Internet,2011,58.2
27,Andalucía,Viviendas que disponen de acceso a Internet,2010,53.1
28,Andalucía,Viviendas que disponen de acceso a Internet,2009,47.3
29,Andalucía,Viviendas que disponen de acceso a Internet,2008,42.2
30,Andalucía,Viviendas que disponen de acceso a Internet,2007,37.5
31,Andalucía,Viviendas que disponen de acceso a Internet,2006,30.7
176,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2021,94.3
177,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2020,93.4
178,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2019,91.1
179,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2018,85.9
180,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2017,81.3
181,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2016,79.7
182,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2015,78.8
183,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2014,72.8
184,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2013,70.7
185,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2012,65.5
186,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2011,60.9
187,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2010,57.3
188,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2009,52.4
189,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2008,50.9
190,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2007,40.6
191,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2006,38.5

In [40]:
grouped_df = filtered_df.groupby(['Comunidades y Ciudades Autónomas', 'Tipo de equipamiento'])

# Plot line charts for each combination
chart_data = None 
for (comunidad, equipamiento), group in grouped_df:
    if chart_data is None:
        chart_data = group[['periodo', 'Total']].set_index('periodo').rename(columns={'Total': comunidad})
    else:
        chart_data = chart_data.merge(group[['periodo', 'Total']].set_index('periodo').rename(columns={'Total': comunidad}), left_index=True, right_index=True)

print(chart_data)

         Andalucía  Asturias (Principado de)
periodo
2021          94.5                      94.3
2020          94.7                      93.4
2019          89.7                      91.1
2018          83.7                      85.9
2017          81.7                      81.3
2016          80.6                      79.7
2015          76.4                      78.8
2014          72.7                      72.8
2013          66.3                      70.7
2012          63.3                      65.5
2011          58.2                      60.9
2010          53.1                      57.3
2009          47.3                      52.4
2008          42.2                      50.9
2007          37.5                      40.6
2006          30.7                      38.5

In [6]:
# filtered_df = df[df['Comunidades y Ciudades Autónomas'].isin(['Andalucía','Asturias (Principado de)'])]
filtered_df = df[df['Tipo de equipamiento']=='Viviendas que disponen de acceso a Internet']
filtered_df = filtered_df[filtered_df['periodo']==2016]
filtered_df

,Comunidades y Ciudades Autónomas,Tipo de equipamiento,periodo,Total
21,Andalucía,Viviendas que disponen de acceso a Internet,2016,80.6
101,Aragón,Viviendas que disponen de acceso a Internet,2016,81.6
181,Asturias (Principado de),Viviendas que disponen de acceso a Internet,2016,79.7
261,Balears (Illes),Viviendas que disponen de acceso a Internet,2016,82.0
341,Canarias,Viviendas que disponen de acceso a Internet,2016,82.1
421,Cantabria,Viviendas que disponen de acceso a Internet,2016,79.6
501,Castilla y León,Viviendas que disponen de acceso a Internet,2016,77.5
581,Castilla-La Mancha,Viviendas que disponen de acceso a Internet,2016,78.2
661,Cataluña,Viviendas que disponen de acceso a Internet,2016,82.9
741,Comunitat Valenciana,Viviendas que disponen de acceso a Internet,2016,80.7
821,Extremadura,Viviendas que disponen de acceso a Internet,2016,79.6
901,Galicia,Viviendas que disponen de acceso a Internet,2016,78.7
981,Madrid (Comunidad de),Viviendas que disponen de acceso a Internet,2016,88.3
1061,Murcia (Región de),Viviendas que disponen de acceso a Internet,2016,81.4
1141,Navarra (Comunidad Foral de),Viviendas que disponen de acceso a Internet,2016,82.5
1221,País Vasco,Viviendas que disponen de acceso a Internet,2016,82.6
1301,Rioja (La),Viviendas que disponen de acceso a Internet,2016,79.2
1381,Ceuta,Viviendas que disponen de acceso a Internet,2016,83.9
1461,Melilla,Viviendas que disponen de acceso a Internet,2016,86.2

In [7]:
import altair as alt

In [7]:
# gdf = gpd.read_file('SECC_CE_20230101.shp'
import fiona
shape = gpd.read_file("SECC_CE_20230101.shp")
shape

,CUSEC,CUMUN,CSEC,CDIS,CMUN,CPRO,CCA,CUDIS,CLAU2,NPRO,NCA,CNUT0,CNUT1,CNUT2,CNUT3,NMUN,geometry
0,0100101001,01001,001,01,001,01,16,0100101,01001,Araba/Ãlava,PaÃ­s Vasco,ES,2,1,1,AlegrÃ­a-Dulantzi,"MULTIPOLYGON (((539753.044 4743324.668, 539784..."
1,0100101002,01001,002,01,001,01,16,0100101,01001,Araba/Ãlava,PaÃ­s Vasco,ES,2,1,1,AlegrÃ­a-Dulantzi,"POLYGON ((539559.740 4745571.157, 539562.677 4..."
2,0100201001,01002,001,01,002,01,16,0100201,01002,Araba/Ãlava,PaÃ­s Vasco,ES,2,1,1,Amurrio,"MULTIPOLYGON (((503618.553 4759559.798, 503620..."
3,0100201002,01002,002,01,002,01,16,0100201,01002,Araba/Ãlava,PaÃ­s Vasco,ES,2,1,1,Amurrio,"POLYGON ((505948.299 4768313.577, 506376.418 4..."
4,0100201003,01002,003,01,002,01,16,0100201,01002,Araba/Ãlava,PaÃ­s Vasco,ES,2,1,1,Amurrio,"POLYGON ((499919.497 4766600.281, 499849.092 4..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36457,4802006025,48020,025,06,020,48,16,4802006,48020,Bizkaia,PaÃ­s Vasco,ES,2,1,3,Bilbao,"POLYGON ((504838.760 4789798.463, 504818.914 4..."
36458,4802007007,48020,007,07,020,48,16,4802007,48020,Bizkaia,PaÃ­s Vasco,ES,2,1,3,Bilbao,"POLYGON ((504960.878 4789408.554, 504957.936 4..."
36459,4802007031,48020,031,07,020,48,16,4802007,48020,Bizkaia,PaÃ­s Vasco,ES,2,1,3,Bilbao,"POLYGON ((504320.024 4788627.067, 504314.276 4..."
36460,4802008016,48020,016,08,020,48,16,4802008,48020,Bizkaia,PaÃ­s Vasco,ES,2,1,3,Bilbao,"POLYGON ((504125.390 4789681.911, 504059.248 4..."
36461,3709201002,37092,002,01,092,37,07,3709201,37092,Salamanca,Castilla y LeÃ³n,ES,4,1,5,Castellanos de Moriscos,"POLYGON ((283038.975 4543703.193, 282904.405 4..."

In [6]:
print(shape.crs)

None